### ISSUE TITLE
node-alarm-dot-com library usage?

### ISSUE THREAD

**Issue by doctorkb** [revenz/node-red-contrib-alarm-dot-com#1]
Have you considered using a library like this one to allow for more feature-ful alarm dot com integration without the upkeep?
https://www.npmjs.com/package/node-alarm-dot-com

I'm happy to help, but I don't know a lot about Node-RED programming yet.

**Comment by revenz** [comment]
havent updated this in 6 years, its dead jim.

but by all means, fork and do whatever you want with it.,
